In [2]:
import numpy as np

In [5]:
# 1. Create a 2-dimensional array
taskOne = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Print the array
print(taskOne)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# 2. Accessing elements in a 2D array
taskTwo = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Accessing the element in the second row (index 1), third column (index 2)
print(taskTwo[1, 2])  # This should print 60

# 1 refers to the second row (indexing starts at 0, so row index 1 is the second row).
# 2 refers to the third column in that row.


60


In [44]:
# 3. Slice a 2d array
taskThree = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# Slice the first two rows and the first two columns
# Expected Output:
# [[1 2]
#  [4 5]]

print(taskThree[0:2, 0:2])

"""
0:2 for rows: It means "start from row 0 and go up to (but not including) row 2."
This selects the first two rows (i.e., rows 0 and 1).

0:2 for columns: It means "start from column 0 and go up to (but not including) column 2."
This selects the first two columns (i.e., columns 0 and 1).
"""

print(taskThree[1:3, 1:3])

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [46]:
# 4. Sum of all elements in a 2d array
taskFour = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
])
# Sum of all elements
# Expected Output: 90

print(np.sum(taskFour))

90


In [56]:
# 5. Row-wise and column-wise sum
taskFive = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# Row-wise sum: [6 15 24]
print(np.sum(taskFive, axis=1))

# Column-wise sum: [12 15 18]
print(np.sum(taskFive, axis=0))

[ 6 15 24]
[12 15 18]


In [ ]:
# 6. Reshape a 2d array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# Reshape to a 4x3 array
# Expected Output:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]


In [ ]:
# 7. Find the max and min of each row
arr = np.array([
    [2, 8, 1],
    [7, 6, 4],
    [5, 9, 3]
])
# Expected Output:
# Row-wise max: [8 7 9]
# Row-wise min: [1 4 3]


In [ ]:
# 8. Transpose a 2d array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# Transposed Output:
# [[1 4 7]
#  [2 5 8]
#  [3 6 9]]


In [ ]:
# 9. Element-wise Multiplication of Two 2D Arrays

In [ ]:
# 10. Matrix multiplication
arr1 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
arr2 = np.array([
    [7, 8],
    [9, 10]
])
# Expected Output:
# [[ 25  28]
#  [ 57  64]
#  [ 89 100]]
